apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "order_notifications_config"
  labels:
    app: orders-monitor-dep
  name: orders-monitor-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-monitor
  template:
    metadata:
      labels:
        app: orders-monitor
    spec:
      containers:
      - image: eu.gcr.io/enduring-range-302623/orders-monitor:v0.1.0
        name: crypto-monitor
        envFrom:
        - configMapRef:
            name: order-notifications-config
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
